CREATE TABLE 'config' ('id' INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 'name' TEXT, 'value' TEXT);
CREATE TABLE 'commands' ('cmid' INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 'code' TEXT, 'description' TEXT, 'type' INTEGER, 'target' TEXT, 'value' TEXT, 'reqperm' INTEGER, 'cost' INTEGER);
CREATE TABLE 'users' ('uid' INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 'uuid' TEXT, 'username' TEXT, 'ip' TEXT, 'lastlogin' DATETIME);
CREATE TABLE 'votesites' ('vid' INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 'site' TEXT, 'worth' INTEGER);
CREATE TABLE 'votes' ('eid' INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 'uid' INTEGER, 'vid' INTEGER, 'created' DATETIME);
